# Generated by Django 4.2.7 on 2026-04-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0016_add_name_fields_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ioannidis_pillar',
            field=models.CharField(choices=[('none', 'Not applicable'), ('methods', 'Methods'), ('reporting', 'Reporting'), ('reproducibility', 'Reproducibility'), ('evaluation', 'Evaluation'), ('incentives', 'Incentives'), ('organization', 'Organization (Harpe 2021)')], default='none', help_text='Mapping to Ioannidis et al. 2015 meta-research pillars (Harpe 2021 adds Organization)', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='reference',
            field=models.TextField(blank=True, help_text='Bibliographic justification for this category'),
        ),
        migrations.AddField(
            model_name='category',
            name='rri_key',
            field=models.CharField(choices=[('none', 'Not applicable'), ('ethics', 'Ethics'), ('public_engagement', 'Public Engagement'), ('gender_equality', 'Gender Equality'), ('science_education', 'Science Education'), ('open_access', 'Open Access'), ('governance', 'Governance')], default='none', help_text='Mapping to Responsible Research and Innovation keys (Stilgoe et al. 2013; Horizon 2020)', max_length=30),
        ),
    ]
