# Generated by Django 4.2.7 on 2026-04-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0017_category_ioannidis_pillar_category_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_short',
            field=models.CharField(blank=True, help_text='Concise headline: what the category studies', max_length=300),
        ),
        migrations.AddField(
            model_name='category',
            name='disambiguation',
            field=models.TextField(blank=True, help_text='Decision rules when this category overlaps with others'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of topic keywords that belong to this category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Full composed description (auto-built from description_short + keywords + disambiguation)'),
        ),
    ]
