# Generated by Django 4.2.7 on 2026-04-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0018_category_description_short_category_disambiguation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="MUI icon name (from @mui/icons-material, e.g. 'Groups', 'Biotech')", max_length=100),
        ),
    ]
