# Generated by Django 4.2.7 on 2026-04-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0019_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='infrastructure',
        ),
        migrations.RemoveField(
            model_name='goldstandard',
            name='infrastructure_mentions',
        ),
        migrations.AddField(
            model_name='classification',
            name='mentions_infrastructure',
            field=models.BooleanField(default=False, help_text='Frontend gate: whether the classifier declared the paper mentions infrastructure/platforms'),
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('url', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('platform', 'Platform'), ('app', 'Mobile/Web App'), ('database', 'Database'), ('network', 'Sensor Network'), ('tool', 'Tool/Software'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='MUI icon name (from @mui/icons-material)', max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names or spellings (admin-curated) — used by search')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Admin-verified canonical entry (vs. user-created)')),
                ('usage_count', models.IntegerField(db_index=True, default=0, help_text='Number of classifications referencing this infrastructure')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who first created this entry (null for seeded/canonical entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_infrastructures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructures',
                'ordering': ['-is_verified', '-usage_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classification',
            name='infrastructures',
            field=models.ManyToManyField(blank=True, help_text='Platforms/apps/databases/tools the paper mentions', related_name='classifications', to='classifications.infrastructure'),
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['-is_verified', '-usage_count'], name='classificat_is_veri_63bff3_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['is_active', 'is_verified'], name='classificat_is_acti_5fd685_idx'),
        ),
    ]
