# Generated by Django 4.2.7 on 2026-04-17 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0021_enable_pg_trgm_for_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAspectSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(db_index=True, default=0, help_text='Number of classifications referencing this suggestion')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Admin-verified canonical entry (vs. user-created)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta-aspect Suggestion',
                'verbose_name_plural': 'Meta-aspect Suggestions',
                'ordering': ['-is_verified', '-usage_count', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='infrastructure',
            name='infrastructure_name_trgm_idx',
        ),
        migrations.AlterField(
            model_name='classification',
            name='meta_aspects',
            field=models.JSONField(blank=True, default=list, help_text='List of meta-research aspect codes (the 7 canonical ones)'),
        ),
        migrations.AddField(
            model_name='metaaspectsuggestion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who first created this entry (null for seeded/canonical entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meta_aspect_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classification',
            name='other_meta_aspects',
            field=models.ManyToManyField(blank=True, help_text='User-proposed meta-aspects not covered by the 7 canonical ones', related_name='classifications', to='classifications.metaaspectsuggestion'),
        ),
        migrations.AddIndex(
            model_name='metaaspectsuggestion',
            index=models.Index(fields=['-is_verified', '-usage_count'], name='classificat_is_veri_a7a19c_idx'),
        ),
        migrations.AddIndex(
            model_name='metaaspectsuggestion',
            index=models.Index(fields=['is_active', 'is_verified'], name='classificat_is_acti_e11c18_idx'),
        ),
    ]
