# Generated by Django 4.2.7 on 2026-04-17 23:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0022_metaaspectsuggestion_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='infrastructure',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='infrastructure_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='metaaspectsuggestion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='metaaspectsugg_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
