# Generated by Django 4.2.7 on 2026-04-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0023_infrastructure_infrastructure_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('debate_comment', 'New comment on your debate'), ('debate_reply', 'Reply to your comment'), ('debate_mention', 'Mentioned in a comment'), ('debate_on_my_abstract', 'New debate on an abstract you classified')], db_index=True, max_length=50),
        ),
    ]
