# Generated by Django 4.2.7 on 2026-04-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0025_userprofile_privacy_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wants_in_acknowledgments',
            field=models.BooleanField(default=False, help_text='Opt-in to appear in platform/paper acknowledgments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wants_paper_collaboration',
            field=models.BooleanField(default=False, help_text='Opt-in to be contacted for potential research paper collaboration'),
        ),
    ]
