# Generated by Django 4.2.7 on 2026-04-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0027_userprofile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.CharField(blank=True, choices=[('biology_life_sciences', 'Biology / Life Sciences'), ('physical_sciences', 'Physics / Chemistry / Earth Sciences'), ('mathematics_theoretical_cs', 'Mathematics / Theoretical Computer Science / Statistics'), ('engineering_applied_cs', 'Engineering / Applied Computing / Technology'), ('medical_health', 'Medical / Health Sciences'), ('social_sciences', 'Social Sciences'), ('humanities', 'Humanities'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', help_text="User's academic background (OECD FOS-inspired, optional)", max_length=30),
        ),
    ]
