# Generated by Django 4.2.7 on 2026-05-24 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0003_abstract_affiliations_abstract_research_areas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0028_alter_userprofile_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('general', 'General (whole corpus)'), ('keyword', 'Keyword'), ('journal', 'Journal')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('journal_name', models.CharField(blank=True, help_text="Set when challenge_type='journal' (matches Abstract.journal exactly)", max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_abstracts', models.PositiveIntegerField(default=0)),
                ('completed_abstracts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['challenge_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Canonical normalized form (lowercased, stripped) — used for matching', max_length=255, unique=True)),
                ('label', models.CharField(help_text="Most common original spelling — used for display (e.g. 'eBird', 'COVID-19')", max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('abstract_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Cached number of abstracts with this keyword (refreshed by populate_keywords)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abstracts', models.ManyToManyField(blank=True, related_name='keywords_rel', to='abstracts.abstract')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['-abstract_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Updated whenever the user classifies within this challenge', null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='classifications.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Participation',
                'verbose_name_plural': 'Challenge Participations',
                'ordering': ['-last_activity_at', '-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='keyword',
            field=models.ForeignKey(blank=True, help_text="Set when challenge_type='keyword'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='classifications.keyword'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['-abstract_count'], name='classificat_abstrac_00eaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['user', '-last_activity_at'], name='classificat_user_id_d5fe8a_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['challenge'], name='classificat_challen_8eaeb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenge_type', 'is_active'], name='classificat_challen_754870_idx'),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(condition=models.Q(('challenge_type', 'general')), fields=('challenge_type',), name='unique_general_challenge'),
        ),
    ]
