# Generated by Django 4.2.7 on 2026-05-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0003_abstract_affiliations_abstract_research_areas_and_more'),
        ('classifications', '0029_challenge_keyword_challengeparticipation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('general', 'General (whole corpus)'), ('keyword', 'Keyword'), ('journal', 'Journal'), ('wos_category', 'WoS Category')], db_index=True, max_length=15),
        ),
        migrations.CreateModel(
            name='WosCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Canonical normalized form (lowercased, stripped) — used for matching', max_length=255, unique=True)),
                ('label', models.CharField(help_text='Most common original spelling — used for display', max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('abstract_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Cached number of abstracts in this category (refreshed by populate_wos_categories)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abstracts', models.ManyToManyField(blank=True, related_name='wos_categories_rel', to='abstracts.abstract')),
            ],
            options={
                'verbose_name': 'WoS Category',
                'verbose_name_plural': 'WoS Categories',
                'ordering': ['-abstract_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='wos_category',
            field=models.ForeignKey(blank=True, help_text="Set when challenge_type='wos_category'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='classifications.woscategory'),
        ),
        migrations.AddIndex(
            model_name='woscategory',
            index=models.Index(fields=['-abstract_count'], name='classificat_abstrac_b72be3_idx'),
        ),
    ]
