# Generated by Django 4.2.7 on 2026-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0030_alter_challenge_challenge_type_woscategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False, help_text='Opt-in to receive the project newsletter by email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
