# Generated by Django 4.2.7 on 2026-10-09 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0031_userprofile_newsletter_opt_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_emails_opt_in',
            field=models.BooleanField(default=True, help_text='Receive reminder/milestone emails about your own activity'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_emails_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EngagementEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('milestone', 'Milestone reached'), ('reengagement_never', 'Re-engagement: never classified'), ('reengagement_lapsed', 'Re-engagement: stopped classifying')], db_index=True, max_length=30)),
                ('dedupe_key', models.CharField(help_text="Why this email was sent; unique per user (e.g. 'milestone:50')", max_length=100)),
                ('recipient_email', models.EmailField(help_text='Address at the time of sending', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='sent', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Numbers used to decide/render (milestone, days inactive, attempt...)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='classificat_user_id_c0d9b0_idx')],
                'unique_together': {('user', 'dedupe_key')},
            },
        ),
    ]
